on:
  pull_request:
    types: [closed]

jobs:
  send-message:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'rice-setup')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for your PR!\nTo claim your free socks fill out this [form](...formlinkhere)'
            })
